name: build-and-lint

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

#backend
jobs:

  backend-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./finance-app/backend 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: financea-app/backend/package-lock.json

      - name: Install Dependencies
        run: npm ci 

      - name: Run ESLint
        run: npm run lint

      - name: Check Formatting
        run: npx prettier --check .

      - name: Build Docker Image (Test)
        run: docker build -t f-backend .

#frontend
  frontend-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./finance-app/frontend 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: finance-app/frontend/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Build React App (Test Compile)
        run: npm run build

      - name: Build Docker Image (Test)
        run: docker build -t f-frontend .